PREFIX sp: <http://spinrdf.org/sp#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

DESCRIBE ?query ?projection ?triple ?order
WHERE {
  ?query a sp:Query ;
    sp:where [ rdf:rest*/rdf:first ?triple ] .
  OPTIONAL {
    ?query sp:resultVariables [ rdf:rest*/rdf:first ?projection ] .
  }
  OPTIONAL {
    ?query sp:orderBy [ rdf:rest*/rdf:first ?order ] .
  }
}
